### PR TITLE
1.12.3 update dependencies

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update dependencies, following changes to `setup.py`:
https://github.com/dpgaspar/Flask-AppBuilder/compare/v1.11.1...v1.12.3

closes #15

### CODE REVIEW

**Comment by xylar** [comment]
This particular version of `flask-appbuilder` is needed by https://github.com/conda-forge/airflow-feedstock/pull/27

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/flask-appbuilder, could you please review this PR?

**Comment by xylar** [comment]
Note: I pointed to the source on GitHub because things were timing out trying to get to pypi, but this seems to be a general problem at the moment, as discussed on [gitter](https://gitter.im/conda-forge/conda-forge.github.io).  If you would prefer that I revert back to pypi, I'm happy to do so.

**Comment by xylar** [comment]
I'm going to give PyPI another chance because it seems like the version numbering doesn't quite match https://github.com/dpgaspar/Flask-AppBuilder/releases, e.g. there's no 2.0.0 on the later whereas there is on PyPI: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/CHANGELOG.rst

**Comment by xylar** [comment]
Thanks @ocefpaf, as always!

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf, as always!

Thanks for helping with this feedstock!

**Pull request merged**
