### PR TITLE
1.13.0 update dependencies

### PR DESCRIPTION
**Pull request by xylar**
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Merge only after #20, #21 and #22 
closes #18

### CODE REVIEW

**Comment by xylar** [comment]
Dependencies `marshmallow-enum` and `prison` are not yet on `conda-forge`.

**Comment by xylar** [comment]
https://pypi.org/project/marshmallow-enum/

https://pypi.org/project/prison/

...a project for another day.

**Comment by xylar** [comment]
I've got PRs in for the missing dependencies: 
https://github.com/conda-forge/staged-recipes/pull/8174
https://github.com/conda-forge/staged-recipes/pull/8175
The missing license from `prison` is likely to be a problem.  If the developer doesn't respond quickly, there's not really anything i can do.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by rjurney** [comment]
@xylar Thanks!

**Pull request merged**
